version: '3.4'

services:
  api-gateway:
    container_name: 'api-gateway'
    restart: 'always'
    build:
      target: api-gateway
      context: .
      dockerfile: ./Dockerfile
    external_links:
      - pubsub-emulator
    depends_on:
      - pubsub-emulator
    ports:
      - '5000:3000'
    env_file: ./env/.api-gateway.env

  user-service:
    container_name: 'user-service'
    restart: 'always'
    build:
      target: user
      context: .
      dockerfile: ./Dockerfile
    external_links:
      - pubsub-emulator
    depends_on:
      - pubsub-emulator
      - api-gateway
    ports:
      - '5001:3000'
  
  notification-service:
    container_name: 'notification-service'
    restart: 'always'
    build:
      target: notification
      context: .
      dockerfile: ./Dockerfile
    external_links:
      - pubsub-emulator
    depends_on:
      - pubsub-emulator
    ports:
      - '5002:3000'

  upload-service:
    container_name: 'upload-service'
    restart: 'always'
    build:
      target: upload
      context: .
      dockerfile: ./Dockerfile
    external_links:
      - pubsub-emulator
    depends_on:
      - pubsub-emulator
    ports:
      - '5003:3000'

  trips-service:
    container_name: 'trips-service'
    restart: 'always'
    build:
      target: trips
      context: .
      dockerfile: ./Dockerfile
    external_links:
      - pubsub-emulator
    depends_on:
      - pubsub-emulator
    ports:
      - '5004:3000'

  pubsub-emulator:
    image: knarz/pubsub-emulator
    container_name: 'pubsub-emulator'
    restart: 'always'
    ports:
      - '8085:8085'
