export enum CommonEnvKey {
  ACCESS_TOKEN_SECRET = 'ACCESS_TOKEN_SECRET',
  GOOGLE_PROJECT_ID = 'GOOGLE_PROJECT_ID',
  GOOGLE_API_JSON_PATH = 'GOOGLE_API_JSON_PATH',
  ACCESS_TOKEN_EXPIRES_IN = 'ACCESS_TOKEN_EXPIRES_IN',
  GOOGLE_LOGGER_CREDENTIAL = 'GOOGLE_LOGGER_CREDENTIAL',
  GOOGLE_PUB_SUB_CREDENTIAL = 'GOOGLE_PUB_SUB_CREDENTIAL',
  PUB_SUB_API_ENDPOINT = 'PUB_SUB_API_ENDPOINT',
  PUB_SUB_PROJECT_ID = 'PUB_SUB_PROJECT_ID',
  NODE_ENV = 'NODE_ENV',
}
