apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  type: ClusterIP
  ports:
  - name: notification-service
    port: 3000
  selector:
    app: notification-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - image: bujosa/acme-explorer-notification
        name: notification-service
        resources:
          limits:
            memory: "1024Mi"
            cpu: "1000m"