apiVersion: v1
kind: Service
metadata:
  name: upload-service
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
  - name: upload-service
    port: 3000
  selector:
    app: upload-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload-service
  template:
    metadata:
      labels:
        app: upload-service
    spec:
      containers:
      - image: bujosa/acme-explorer-upload
        name: upload-service
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"

