export enum EnvKey {
  PORT = 'PORT',
  PUB_SUB_PROJECT_ID = 'PUB_SUB_PROJECT_ID',
  PUB_SUB_API_ENDPOINT = 'PUB_SUB_API_ENDPOINT',
  AWS_ACCESS_KEY = 'AWS_ACCESS_KEY',
  AWS_SECRET_KEY = 'AWS_SECRET_KEY',
  AWS_REGION = 'AWS_REGION',
  BUCKET_NAME = 'BUCKET_NAME',
  SPACE_ENDPOINT = 'SPACE_ENDPOINT'
}
