export enum EnvKey {
  GOOGLE_SERVICE_ACCOUNT = 'GOOGLE_SERVICE_ACCOUNT',
  MONGO_DB_URI = 'MONGO_DB_URI',
  PUB_SUB_PROJECT_ID = 'PUB_SUB_PROJECT_ID',
  PUB_SUB_API_ENDPOINT = 'PUB_SUB_API_ENDPOINT',
  PORT = 'PORT',
  REFRESH_TOKEN_SECRET = 'REFRESH_TOKEN_SECRET',
  REFRESH_TOKEN_EXPIRES_IN = 'REFRESH_TOKEN_EXPIRES_IN',
  GOOGLE_INSPECTIONS_APP_SERVICE_ACCOUNT = 'GOOGLE_INSPECTIONS_APP_SERVICE_ACCOUNT'
}
