export enum CommonEnvKey {
  ACCESS_TOKEN_SECRET = 'ACCESS_TOKEN_SECRET',
  GOOGLE_PROJECT_ID = 'GOOGLE_PROJECT_ID',
  GOOGLE_API_JSON_PATH = 'GOOGLE_API_JSON_PATH',
  ACCESS_TOKEN_EXPIRES_IN = 'ACCESS_TOKEN_EXPIRES_IN',
  ALLOW_HOST_HEADER = 'ALLOW_HOST_HEADER',
  GOOGLE_LOGGER_CREDENTIAL = 'GOOGLE_LOGGER_CREDENTIAL',
  GOOGLE_PUB_SUB_CREDENTIAL = 'GOOGLE_PUB_SUB_CREDENTIAL',
  NODE_ENV = 'NODE_ENV'
}
