export enum EnvKey {
  PORT = 'PORT',
  WALLET_SERVICE = 'WALLET_SERVICE',
  UPLOAD_SERVICE = 'UPLOAD_SERVICE',
  BUY_SERVICE = 'BUY_SERVICE',
  CATALOGUE_SERVICE = 'CATALOGUE_SERVICE',
  CLOUD_FUNCTION = 'CLOUD_FUNCTION',
}
